### ISSUE TITLE
add_vertex! Appears to add multiple copies of a vertex

### ISSUE THREAD

**Issue by JoeyT1994** [mtfishman/NamedGraphs.jl#10]
See the below:

![image](https://user-images.githubusercontent.com/51231103/202577788-4528c913-9d57-462c-ab9e-e46b3bc3b2e1.png)

I get this issue with NamedDimGraphs as well.

**Comment by mtfishman** [comment]
Thanks for the report, that's pretty weird behavior.

**Comment by mtfishman** [comment]
This should be fixed in the latest version.
