### ISSUE TITLE
Make `hexagonal_lattice_graph` more consistent between periodic and non-periodic

### ISSUE THREAD

**Issue by mtfishman** [mtfishman/NamedGraphs.jl#57]
Changing the setting of `periodic` in `hexagonal_lattice_graph` changes the lattice size:
```julia
julia> using NamedGraphs

julia> nv(hexagonal_lattice_graph(2, 2; periodic=false))
16

julia> nv(hexagonal_lattice_graph(2, 2; periodic=true))
8
```
I think instead it should output graphs with the same number of vertices and structure, just with extra periodic edges if `periodic=true`. It is implemented that way right now because the periodic graphs are constructed by first constructing the corresponding non-periodic version of the lattice and then merging vertices, it could still be implemented that way with some code restructuring, for example having an inner non-periodic version which the periodic version calls. The current design makes it difficult to reason about what size lattice will get output. (@JoeyT1994)

**Comment by mtfishman** [comment]
You're probably right. I think I was partially confused by #59, and not being sure how to interpret `m` and `n` in `hexagonal_lattice_graph(m, n; periodic)` in the case of `periodic=true`. Can I think of `m` and `n` as the number of rows and columns of hexagons, whether or not `periodic=true`? I can see why, in that case, the number of vertices won't be the same between `periodic=true` and `false`, since there are boundary vertices that are shared across the periodic boundary.

**Comment by JoeyT1994** [comment]
Yeah `m` and `n` are the numbers of rows and columns of hexagons. If you then set the `periodic` flag to `true` it will build the `m` rows and `n` columns of hexagons but then "fuse" the right-most column with the left-most one and "fuse" the top-most row with the bottom-most one
