### ISSUE TITLE
Naming convention for `NamedGraph` graph generators

### ISSUE THREAD

**Issue by JoeyT1994** [mtfishman/NamedGraphs.jl#60]
Going forward we should always adopt the naming convention that  functions `f` which generate `NamedGraph` types are prefixed with `named_f` whilst the SimpleGraph version is simply `f`. 

So for instance having `named_hexagonal_lattice_graph` versus `hexagonal_lattice_graph`  and `named_triangular_lattice_graph` versus `triangular_lattice_graph`  (two instances where we currently don't follow that convention).

We should also introduce:

`named_random_regular`, `named_uniform_tree` and others from [https://juliagraphs.org/Graphs.jl/dev/core_functions/simplegraphs_generators/] we wish to have easy constructors for.

**Comment by mtfishman** [comment]
Closed by #64.
